### PR TITLE
Fixed ImportError: cannot import name 'Iterable' from 'collections' f…

### PR DESCRIPTION
**Pull request by cenjui**
Fixed ImportError: cannot import name 'Iterable' from 'collections' for python 3.10 and above.

### CODE REVIEW

**Review by oualib — APPROVED** [review]

**Review by oualib — APPROVED** [review]
Can we merge those changes to make it work in Python 3.10?

**Comment by oualib** [comment]
@cenjui is it possible to merge the changes? We can not use this module for Python 3.10+.

**Comment by cenjui** [comment]
@oualib  I dont think so - Github still reports:

"At least 1 approving review is required by reviewers with write access. "

Unless I am missing something obvious?

**Review by rob-potter — APPROVED** [review]

**Comment by tomghyselinck** [comment]
Hi, the maintainer of this project is no longer responding.

We created a fork which addresses this issue and did some other code improvements: https://github.com/excentis/python-highcharts

We released it on PyPI too: https://pypi.org/project/highcharts-excentis/

**Review by fevrec — APPROVED** [review]

**Review by fevrec — APPROVED** [review]
